license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
authors="antthLuca"
description='''
Need raw ore but don't want to mine? Do you look at your ore farm and think, “Useless”? Not anymore!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
